import Message from "@/design-system/components/Message";
import Head from "next/head";
import Link from "next/link";
import Button from "devextreme-react/button";
import React from "react";

export default function Home() {
  return (
    <React.Fragment>
      <Head>
        <title>Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main style={{ padding: "1em" }}>
        <h1>Olá!</h1>
        <div
          style={{
            height: 1,
            background: "lightgrey",
            marginTop: 3,
            marginBottom: "1em",
          }}
        />

        <Message
          type="info"
          header="Você ainda não possui inventários."
          content={
            <div style={{ marginTop: "0.5em" }}>
              <Button>
                <Link
                  href={"/inventory/create"}
                  style={{
                    textDecoration: "none",
                    color: "inherit",
                  }}
                >
                  Criar inventário
                </Link>
              </Button>
            </div>
          }
        />
      </main>
    </React.Fragment>
  );
}
